version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codedeploy
hooks:
  ApplicationStop:
    - location: codedeploy/properties.sh
      timeout: 300
      runas: root
    - location: codedeploy/common.sh
      timeout: 300
      runas: root
    - location: codedeploy/stop_service.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy/remove_service_root.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/download_bundle.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_service.sh
      timeout: 300
      runas: root
