version: 0.0
os: linux
#files:
#  - source: /
#    destination: /home/ubuntu/codedeploy
#    overwrite: true
hooks:
  ApplicationStop:
    - location: codedeploy/stop_service.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy/remove_service_root.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/download_bundle.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_service.sh
      timeout: 300
      runas: root
